version: "3.7"

volumes:
  db:

services:
  db:
    image: mariadb:10.5
    restart: always
    networks:
      - gnet
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=gobot
      - MYSQL_USER=gobot

  gobot_driver:
    image: braidgo/gobot-driver:latest
    restart: always
    networks:
      - gnet
    depends_on:
      - db
    command: "-no_database=false -report_limit 100 -batch_size 1024 -script_path scipt/"
    ports:
      - 8888:8888
    deploy:
      resources:
        limits:
          cpus: "2"
    environment:
      - MYSQL_PASSWORD=gobot
      - MYSQL_DATABASE=gobot
      - MYSQL_USER=gobot
      - MYSQL_HOST=db

networks:
  gnet:
    driver: bridge
