name: gobot ci

on:
  [push]

jobs:

  build:
    runs-on: ubuntu-20.04
    env:
      GOPATH: "${{github.workspace}}/go"
      SRCDIR: "go/src/github.com/pojol/gobot"

    steps:
    - uses: actions/checkout@v2
      with:
        path: ${{env.SRCDIR}}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
    
    - name: Build gobot
      run: go build -o bot_linux
        
    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_NAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: braidgo/gobot-driver:$(date +%s)